name: subsera
description: A Flutter mobile app that generates 5 videos based on user input.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.1
  youtube_player_flutter: ^9.0.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  http: ^1.1.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_inappwebview: ^6.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/images/